name: currencyx
description: "currency real time echange rate provider"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0-56.0.dev

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  retrofit: ^4.9.2
  logger: ^2.6.0
  json_annotation: ^4.9.0
  intl: ^0.18.1
  flutter_svg: ^2.2.3
  get_it: ^8.0.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^10.2.1
  build_runner: ^2.10.4
  json_serializable: ^6.11.3
  pretty_dio_logger: ^1.4.0
  flutter_svg: ^2.2.3
  flutter_dotenv: ^6.0.0
  get_it: ^8.0.2
  flutter_lints: ^6.0.0

targets:
  $default:
    builders:
      retrofit_generator:
        options:
          format_output: true
          auto_cast_response: true
          empty_request_body: false
          use_result: false

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/roboto_thin.ttf
          weight: 100
        - asset: fonts/roboto_extralight.ttf
          weight: 200
        - asset: fonts/roboto_light.ttf
          weight: 300
        - asset: fonts/roboto_regular.ttf
          weight: 400
        - asset: fonts/roboto_medium.ttf
          weight: 500
        - asset: fonts/roboto_bold.ttf
          weight: 700
        - asset: fonts/roboto_extrabold.ttf
          weight: 800
  assets:
    - assets/
    - secrets.env
